### ISSUE TITLE
[Back] Tratar o erro de e-mail duplicado e retornar uma mensagem clara para o usuário.

### ISSUE THREAD

**Issue by tauanesales** [tauanesales/BACK-MATC84-LABORATORIO-DE-PROGRAMACAO-WEB#90]
# Endpoint: POST `/auth/register`

## Evidência do erro
![2024-06-20_22-35](https://github.com/tauanesales/BACK-MATC84-LABORATORIO-DE-PROGRAMACAO-WEB/assets/62819445/915a3b0e-5fd5-43bc-9af0-82a316cdcd17)

## Sugestão de solução
Ao receber a requisição de criação do usuário, pesquisar no banco de dados se ele já existe.
    - Se não existir, seguir o fluxo como ele já atualmente acontece;
    - Se existir, retornar [409](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-p2-semantics-18#section-7.4.10) com uma mensagem explicando o erro que ocorreu. (Ex.: `{ "error": "E-mail já cadastrado." }`. 

# Task relacionada
- https://github.com/tauanesales/FRONT-MATC84-LABORATORIO-DE-PROGRAMACAO-WEB/issues/63

**Comment by Everton-Wallace-Oliveira** [comment]
Corrigido
