### ISSUE TITLE
[Back] Uma mensagem genérica deve ser retornada para erros inesperados.

### ISSUE THREAD

**Issue by tauanesales** [tauanesales/BACK-MATC84-LABORATORIO-DE-PROGRAMACAO-WEB#91]
# Descrição

Ao receber requisições, quando há um erro qualquer no servidor, é retornado para o usuário exatamente o erro que ocorreu. Isso é um problema de segurança. Não é para o usuário ter acesso a, por exemplo, exatamente o erro que aconteceu no banco de dados.

- Erros devem ser processados e retornados corretamente quando possível (task associada #90);
- Uma mensagem genérica deve ser retornada para erros inesperados (essa task).

# Onde corrigir

- Todas as controllers e algumas services.

# Evidência
![image](https://github.com/tauanesales/BACK-MATC84-LABORATORIO-DE-PROGRAMACAO-WEB/assets/62819445/484add4f-8550-4cfd-915d-24df159e3fdd)
![image](https://github.com/tauanesales/BACK-MATC84-LABORATORIO-DE-PROGRAMACAO-WEB/assets/62819445/6cedc98e-582d-40ad-b816-8a907c6a57d2)
![image](https://github.com/tauanesales/BACK-MATC84-LABORATORIO-DE-PROGRAMACAO-WEB/assets/62819445/9abe73e1-5155-4b2b-b372-5db840dc11d4)

# Sugestão de solução

- [ ] Procurar por try-catches e retornos HTTP `500` em todos os arquivos e alterar a mensagem de retorno de todos eles;
    - Mudar o retorno de `return res.status(500).json({ error: error.message });` para `return res.status(500).json({ error: "Internal Server Error" });`

**Comment by Everton-Wallace-Oliveira** [comment]
Corrigido

**Comment by tauanesales** [comment]
FIXED BY #92
